server:
  port: 9010

spring:
  application:
    name: "risk-management-service"
  datasource:
    url: jdbc:mysql://localhost:3309/riskdatabase
    username: myuser
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

