server:
  port: 9000

spring:
  application:
    name: "order-management-service"
  datasource:
    url: jdbc:mysql://localhost:3308/orderdatabase
    username: myuser
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    function:
      definition: processSignal
    stream:
      bindings:
        processSignal-in-0:
          destination: signal-sent
          group: ${spring.application.name}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


