server:
  port: 8090

spring:
  application:
    name: "trade-engine-service"
  cloud:
    function:
      definition: generateSignal
    stream:
      bindings:
        generateSignal-out-0:
          destination: signal-sent
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:mysql://localhost:3307/signaldatabase
    username: myuser
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
